### ISSUE TITLE
stream opens to the top, but new posts are on the bottom

### ISSUE THREAD

**Issue by caseyls** [steve228uk/PeachMac#26]
If it opened to the bottom, showing the most recent post when you clicked on someone that'd be awesome!

**Comment by steve228uk** [comment]
Thanks @caseyls!

This should actually be fixed in the latest build. Are you able to test this one for me and let me know if the issue persists?

http://sht.tl/6hkj65

**Comment by caseyls** [comment]
It’s fixed! I tried building it myself last night because I saw a commit that looked like you fixed it but I couldn’t figure out how to open it after I ran the pod install command. I’m very bad at this 😅

Thanks a ton!

**Comment by steve228uk** [comment]
@caseyls No problem! You'll need Xcode to run it after you've run `pod install`
